name: Linting CI/CD

on:
  push:
    branches: 
      - 'main'
    tags: [v*]
  workflow_dispatch:

jobs:
  build_and_coverage_report:
    runs-on: ubuntu-latest

    steps:
      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.2

     
