name: reviewdog
on: [push, pull_request]
jobs:
  checkstyle:
    name: run checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@v0.5.1
