name: Run CheckStyle for Java Files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkstyle for Java
    - uses: dbelyaev/action-checkstyle@v0.6.1
